export const GET_TRENDING_SUCCESS = 'GET_TRENDING_SUCCESS'
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS'
export const GET_TV_LIST_SUCCESS = 'GET_TV_LIST_SUCCESS'
export const GET_MOVIE_LIST_ALL_SUCCESS = 'GET_MOVIE_LIST_ALL_SUCCESS'